id = "unocss"
name = "UnoCSS"
description = "UnoCSS support"
version = "0.0.3"
schema_version = 1
authors = ["Raunak Raj <bajrangcoders@gmail.com>"]
repository = "https://github.com/bajrangCoder/zed-unocss"

[language_servers.unocss-language-server]
name = "UnoCSS Language Server"
languages = [
    "Astro",
    "HTML",
    "JavaScript",
    "TSX",
    "Svelte",
    "Elixir",
    "HEEX",
    "ERB",
    "PHP",
    "Vue.js",
]
